import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  route("login", "routes/auth.login.tsx"),
  route("logout", "routes/auth.logout.ts"),
  route("change-password", "routes/auth.change-password.tsx"),
  route("health/live", "routes/health.live.ts"),
  route("health/ready", "routes/health.ready.ts"),
  layout("routes/app.tsx", [
    index("routes/app.dashboard.tsx"),
    route("dashboard-mode", "routes/app.dashboard-mode.ts"),
    route("pos/issue", "routes/app.pos.issue.tsx"),
    route("balances", "routes/app.balances.tsx"),
    route("stock-in/new", "routes/app.stock-in.new.tsx"),
    route("issues/new", "routes/app.issues.new.tsx"),
    route("approvals", "routes/app.approvals.tsx"),
    route("notifications", "routes/app.notifications.ts"),
    route("returns", "routes/app.returns.tsx"),
    route("returns/bus", "routes/app.returns.bus.tsx"),
    route("receipts/:id", "routes/app.receipts.$id.tsx"),
    route("job-cards", "routes/app.job-cards._index.tsx"),
    route("job-cards/new", "routes/app.job-cards.new.tsx"),
    route("job-cards/:id", "routes/app.job-cards.$id.tsx"),
    route("tyres", "routes/app.tyres.tsx"),
    route("tyres/dag", "routes/app.tyres.dag.tsx"),
    route("transfers", "routes/app.transfers._index.tsx"),
    route("transfers/new", "routes/app.transfers.new.tsx"),
    route("purchases", "routes/app.purchases._index.tsx"),
    route("purchases/new", "routes/app.purchases.new.tsx"),
    route("alerts/low-stock", "routes/app.alerts.low-stock.tsx"),
    route("parts", "routes/app.parts.tsx"),
    route("parts/print-labels", "routes/app.parts.print-labels.tsx"),
    route("scan", "routes/app.scan.tsx"),
    route("categories", "routes/app.categories.tsx"),
    route("tires/conversion", "routes/app.tires.conversion.tsx"),
    route("buses", "routes/app.buses.tsx"),
    route("buses/:id", "routes/app.buses.$id.tsx"),
    route("suppliers", "routes/app.suppliers.tsx"),
    route("reports/movements", "routes/app.reports.movements.tsx"),
    route("reports/daily-movement", "routes/app.reports.daily-movement.tsx"),
    route("reports/fast-moving", "routes/app.reports.fast-moving.tsx"),
    route("reports/bus-usage", "routes/app.reports.bus-usage.tsx"),
    route("reports/item-usage", "routes/app.reports.item-usage.tsx"),
    route("reports/unusual-issues", "routes/app.reports.unusual-issues.tsx"),
    route("reports/daily-issues", "routes/app.reports.daily-issues.tsx"),
    route("reports/dag-out", "routes/app.reports.dag-out.tsx"),
    route("reports/transfers", "routes/app.reports.transfers.tsx"),
    route("reports/purchases", "routes/app.reports.purchases.tsx"),
    layout("routes/admin.tsx", [
      route("admin/users", "routes/admin.users.tsx"),
      route("admin/stores", "routes/admin.stores.tsx"),
      route("admin/reorder", "routes/admin.reorder.tsx"),
      route("admin/corrections", "routes/admin.corrections.tsx"),
      route("admin/audit", "routes/admin.audit.tsx"),
    ]),
  ]),
] satisfies RouteConfig;
